### ISSUE TITLE
product edit crash with complement spamexeprts.

### ISSUE THREAD

**Issue by zubeldialuis** [SpamExperts/whmcs-addon#7]
### Version information
1.0

### Steps to replicate

 1. add spamexperts to a complement hosting product. then add a order with this complement for a customer.

### Actual result
when i try to manage the hosting product from bakend: /panel/admin/clientsservices.php?userid=19&id=30 i get an error page. in my apache server logs i get this error:
```
AH01071: Got error 'PHP message: [WHMCS Application] ERROR: Error: Call to a member function assign() on null in /var/www/vhosts/iontics.com/httpdocs/panel/modules/servers/kwspamexperts/kwspamexperts.php:300 Stack trace: #0 /var/www/vhosts/iontics.com/httpdocs/panel/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): kwspamexperts_ClientArea(Array) #1 /var/www/vhosts/iontics.com/httpdocs/panel/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\\Module\\AbstractModule->call('ClientArea', Array) #2 /var/www/vhosts/iontics.com/httpdocs/panel/vendor/whmcs/whmcs-foundation/lib/Service.php(0): WHMCS\\Module\\Server->call('ClientArea') #3 /var/www/vhosts/iontics.com/httpdocs/panel/admin/clientsservices.php(0): WHMCS\\Service->getAddons() #4 {main} {"exception":"[object] (Error(code: 0): Call to a member function assign() on null at /var/www/vhosts/iontics.com/httpdocs/panel/modules/servers/kwspamexperts/kwspamexperts.php:300)"} []\n', referer: https://www.iontics.com/panel/admin/clientsdomains.php?userid=19
```
### Expected result

can edit the product.

**Comment by georgianiorgu1** [comment]
Fix verified.
